name = "Craftoria (1)"
author = "TeamAOE"
version = "1.36.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a0bb7f0fcdfab17c58c40a957a4b1944c3fdab54dae42fde3c735dde30e397b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
