name = "Craftoria (1)"
author = "TeamAOE"
version = "1.36.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1fb24c6018a4c1a910e0653c5369aaee7f1d14cbb79381cd18195eb580fde2e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
