#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Sep 23 07:11:11 IDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
